version: "1"
services:
  udx-worker:
    container_name: udx-worker
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=udx-worker
    volumes:
      - ./src/app:/home/app
    ports:
      - 8080:8080
    tty: true
    stdin_open: true
