version: "1"
services:
  udx-worker:
    container_name: udx-worker
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=udx-worker
    environment:
      TYPE: cli #env
    volumes:
      - ./src/app:/home/app
    tty: true
    stdin_open: true
    command: tail -f /dev/null
