version: "1"
services:
  udx-worker-service:
    container_name: udx-worker-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=udx-worker
    environment:
      ENV_TYPE: service
    volumes:
      - ./src/app:/home/app
    tty: true
    stdin_open: true
  udx-worker-task:
    container_name: udx-worker-task
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=udx-worker
    environment:
      ENV_TYPE: task
      TOOL: NodeJS
    volumes:
      - ./src/task:/home/app
    tty: true
    stdin_open: true
