version: "1"
services:
  # Service (Web Server, API, etc.)
  udx-worker-service:
    container_name: udx-worker-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=udx-worker
        - APP_PATH=./fixtures/apps/service/*
    environment:
      ENV_TYPE: service
    tty: true
    stdin_open: true

  # Task (CI/CD pipelines jobs/tasks, webhooks, tooling, templates, etc.)
  # udx-worker-task:
  #   container_name: udx-worker-task
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - USER=udx-worker
  #       - APP_PATH=./fixtures/apps/task/*
  #   environment:
  #     ENV_TYPE: task
  #     TOOL: NodeJS
  #   tty: true
  #   stdin_open: true
