---
kind: workerCertificates
version: udx.io/worker-v1/certificates
items:
  worker-vm:
    name: "WORKER_WM"
    notes: "Worker VM certificate"
    source: azure/worker-vm-cert
    has_private_key: true
    type: certificate
