---
kind: workerConfig
version: udx.io/worker-v1/config
config:
  env:
    DOCKER_IMAGE_NAME: "udx-worker"
  workerSecrets:
    AZURE_SECRET: <https://keyvault.azure.com/v3/your-secret-id>
    GCP_SECRET: <https://secretmanager.googleapis.com/v1/projects/your-project/secrets/your-secret>
  workerActors:
    - type: azure-service-principal
      subscription: your-azure-subscription-id
      tenant: your-azure-tenant-id
      application: your-azure-application-id
      password: "udx://tokens/data/azure-service-principal/secretValue"
    - type: gcp-service-account
      email: your-gcp-service-account-email
      keyfile: "udx://tokens/data/gcp-service-account/keyfile"
  volumes:
    - "/host/path:/container/path"
