---
kind: workerConfig
version: udx.io/worker-v1/config
config:
  variables:
    DOCKER_IMAGE_NAME: "udx-worker"
  secrets:
    NEW_RELIC_API_KEY: "new_relic_api_key"
  actors:
    - type: gcp-service-account
      email: ${GCP_SERVICE_ACCOUNT_EMAIL}
      keyfile: ""
