---
kind: workerConfig
version: udx.io/worker-v1/config
config:
  variables:
    DOCKER_IMAGE_NAME: "udx-worker"
  secrets:
    NEW_RELIC_API_KEY: "azure/new_relic_api_key"
    OCTOPUS_API_KEY: "bitwarden/octetopus_api_key"
    SLACK_API_KEY: "aws/slack_api_key"
    K8S_PRIVATE_KEY: "gcp/k8s_private_key"
  actors:
    - type: azure
      creds_file: "${AZURE_CREDS_FILE}"
    - type: aws
      creds_file: "${AWS_CREDS_FILE}"
    - type: gcp
      creds_file: "${GCP_CREDS_FILE}"
    - type: bitwarden
      creds_file: "${BITWARDEN_CREDS_FILE}"
