kind: workerConfig
version: udx.io/worker-v1/config
config:
  variables:
    DOCKER_IMAGE_NAME: "udx-worker"
  secrets:
    NEW_RELIC_API_KEY: "$secret_url"
  actors:
    - type: gcp-service-account
      email: ${GCP_SERVICE_ACCOUNT_EMAIL}
      keyfile: ${GCP_KEYFILE_CONTENT}
