kind: workerConfig
version: udx.io/worker-v1/config
config:
  env:
    AZURE_SUBSCRIPTION_ID: 132583e0-0e9d-46a9-b702-66060ca58c1b
    AZURE_TENANT_ID: ffbbef27-e47d-46b3-8d3c-21aa3438d682
    AZURE_APPLICATION_ID: a6319a29-b3f2-4fc9-ba16-f215664a7d4e
    DOCKER_IMAGE_NAME: udx-worker
  workerSecrets:
    AZURE_SECRET: "https://kv-udx-worker-secrets.vault.azure.net/secrets/udx-worker-secret-one"
  workerActors:
    - type: azure-service-principal
      subscription: ${AZURE_SUBSCRIPTION_ID}
      tenant: ${AZURE_TENANT_ID}
      application: ${AZURE_APPLICATION_ID}
      password: ${AZURE_APPLICATION_PASSWORD}