---
kind: workerConfig
version: udx.io/worker-v1/config
config:
  variables:
    DOCKER_IMAGE_NAME: "udx-worker"
  secrets:
    NEW_RELIC_API_KEY: "gcp/rabbit-ci-tooling/new_relic_api_key"

    # Examples:
    #
    # NEW_RELIC_API_KEY: "azure/kv-udx-worker/new_relic_api_key"
    # NEW_RELIC_API_KEY: "aws/secrets-manager/new_relic_api_key"
    # NEW_RELIC_API_KEY: "bitwarden/collection/new_relic_api_key"
    #
  actors:
    - type: gcp
      creds: "${GCP_CREDS}"

    # Examples:
    #
    # - type: azure
    #   creds: "${AZURE_CREDS}"
    #
    # - type: aws
    #   creds: "${AWS_CREDS}"
    #
    # - type: bitwarden
    #   creds: "${BITWARDEN_CREDS}"
    #
