command: app
actions:
  create:
    params:
      - type:
          isrequired: true
          prompt:
            type: text
            message: Please enter the type of app to create
    example: udx-worker app create react-app
  test:
    params:
      - name:
          isrequired: true
          prompt:
            type: text
            message: Please enter the name of the app to test
    example: udx-worker app test react-app
  build:
    params:
      - name:
          isrequired: true
          prompt:
            type: text
            message: Please enter the name of the app to build
    example: udx-worker app build react-app
  deploy:
    params:
      - name:
          isrequired: true
          prompt:
            type: text
            message: Please enter the name of the app to deploy
    example: udx-worker app deploy react-app
description: App Commands Helper
module: App
