name: Build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      RELEASE_BRANCH_REF: refs/heads/latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        # if: success() && github.ref != ${{ env.RELEASE_BRANCH_REF }}
        run: docker build .

      - uses: actions/setup-dotnet@v3
        # if: success() && github.ref == ${{ env.RELEASE_BRANCH_REF }}
        with:
          dotnet-version: "3.1.x"

      - name: Install GitVersion
        # if: success() && github.ref == ${{ env.RELEASE_BRANCH_REF }}
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.5.0"

      - name: Determine Version
        # if: success() && github.ref == ${{ env.RELEASE_BRANCH_REF }}
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
          configFilePath: ci/git-version.yml

      - name: Authenticate to Google Cloud
        id: google_auth
        # if: success() && github.ref == ${{ env.RELEASE_BRANCH_REF }}
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ vars.GCP_AUTH_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      - name: Set up Google Cloud SDK
        # if: success() && github.ref == ${{ env.RELEASE_BRANCH_REF }}
        uses: google-github-actions/setup-gcloud@v1

      - name: Login to Google Artifact Registry
        # if: success() && github.ref == ${{ env.RELEASE_BRANCH_REF }}
        run: |
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Delete previous latest image
        # if: success() && github.ref == ${{ env.RELEASE_BRANCH_REF }}
        run: |
          IMAGE_NAME="${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/${{ vars.GCP_REGISTRY_REPO }}/${{ vars.DOCKER_IMAGE_NAME }}"
          IMAGE_TAG="latest"
          IMAGE_DIGEST=$(gcloud container images list-tags ${IMAGE_NAME} --filter="tags:${IMAGE_TAG}" --format='get(digest)')
          if [ -n "$IMAGE_DIGEST" ]; then
            gcloud container images delete "${IMAGE_NAME}@${IMAGE_DIGEST}" --force-delete-tags --quiet
          else
            echo "Image with tag 'latest' does not exist. Skipping delete."
          fi

      - name: Docker Login
        # if: success() && github.ref == ${{ env.RELEASE_BRANCH_REF }}
        run: |
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev
          docker login -u oauth2accesstoken -p "${{ steps.google_auth.outputs.access_token }}" ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Build and push images
        # if: success() && github.ref == ${{ env.RELEASE_BRANCH_REF }}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/${{ vars.GCP_REGISTRY_REPO }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ steps.gitversion.outputs.semVer }}
            ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/${{ vars.GCP_REGISTRY_REPO }}/${{ vars.DOCKER_IMAGE_NAME }}:latest

      - name: Generate changelog
        # if: success() && github.ref == ${{ env.RELEASE_BRANCH_REF }}
        id: changelog
        run: |
          echo "::set-output name=changelog::$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %s")"

      - name: Create GitHub release
        # if: success() && github.ref == ${{ env.RELEASE_BRANCH_REF }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.gitversion.outputs.semVer }}
          release_name: Release v${{ steps.gitversion.outputs.semVer }}
          body: |
            Release Notes:
            ${{ steps.changelog.outputs.changelog }}
