name: Build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        if: github.ref != 'refs/heads/latest'
        run: docker build .

      - name: Authenticate to Google Cloud
        # if: github.ref == 'refs/heads/latest'
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ vars.GCP_AUTH_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      - name: Login to Google Artifact Registry
        # if: github.ref == 'refs/heads/latest'
        run: |
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev
          docker login -u oauth2accesstoken -p "$(gcloud auth print-access-token ${{ vars.GCP_SERVICE_ACCOUNT }} --impersonate-service-account)" ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Install GitVersion
        # if: github.ref == 'refs/heads/latest'
        run: dotnet tool install --global GitVersion.Tool

      - name: Use GitVersion
        # if: github.ref == 'refs/heads/latest'
        id: version
        run: echo ::set-output name=VERSION::$(dotnet gitversion /showvariable SemVer)

      - name: Build and push images
        # if: github.ref == 'refs/heads/latest'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/${{ vars.GCP_REGISTRY_REPO }}:${{ steps.version.outputs.VERSION }}
            ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/${{ vars.GCP_REGISTRY_REPO }}:latest

      - name: Generate changelog
        # if: github.ref == 'refs/heads/latest'
        id: changelog
        run: |
          echo "::set-output name=changelog::$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %s")"

      - name: Create GitHub release
        # if: github.ref == 'refs/heads/latest'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          release_name: Release v${{ steps.version.outputs.VERSION }}
          body: |
            Release Notes:
            ${{ steps.changelog.outputs.changelog }}
