name: Build and Test Docker Image

on:
  push:
    branches-ignore:
      - latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Development Pipeline
        run: make dev-pipeline DEBUG=false
        working-directory: .

      - name: Download Trivy
        uses: aquasecurity/trivy-action@0.24.0

      - name: Run Trivy scan on Docker image
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 1 udx-worker:latest
