name: Release UDX Worker

on:
  push:
    branches-ignore:
      - latest

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
      changelog: ${{ steps.changelog.outputs.changelog }}
    env:
      FORCE: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate .udx file
        run: |
          echo "AZURE_SUBSCRIPTION_ID=${{ vars.AZURE_SUBSCRIPTION_ID }}" > .udx
          echo "AZURE_TENANT_ID=${{ vars.AZURE_TENANT_ID }}" >> .udx
          echo "AZURE_APPLICATION_ID=${{ vars.AZURE_APPLICATION_ID }}" >> .udx
          echo "AZURE_APPLICATION_PASSWORD=${{ secrets.AZURE_APPLICATION_PASSWORD }}" >> .udx

      - name: Run Development Pipeline
        run: make dev-pipeline DEBUG=false

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v2
        with:
          versionSpec: "5.12.0"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v2
        with:
          useConfigFile: true
          configFilePath: ci/git-version.yml

      - name: Generate changelog
        id: changelog
        run: |
          git log $(git describe --tags --abbrev=0)..HEAD -- . --pretty=format:"- %s" > changelog.txt
          CHANGELOG=$(cat changelog.txt | jq -sRr @uri)
          echo "changelog<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

  google-release:
    runs-on: ubuntu-latest
    needs: test-pipeline
    permissions:
      contents: write
      id-token: write
    env:
      FORCE: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate to Google Cloud
        id: google_auth
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ vars.GCP_AUTH_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Login to Google Artifact Registry
        run: gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Delete previous "latest" image from Google Artifact Registry
        run: |
          IMAGE_NAME="${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/${{ vars.GCP_REGISTRY_REPO }}/${{ vars.DOCKER_IMAGE_NAME }}"
          IMAGE_TAG="latest"
          IMAGE_DIGEST=$(gcloud container images list-tags ${IMAGE_NAME} --filter="tags:${IMAGE_TAG}" --format='get(digest)')
          if [ -n "$IMAGE_DIGEST" ]; then
            gcloud container images delete "${IMAGE_NAME}@${IMAGE_DIGEST}" --quiet --force-delete-tags
          else
            echo "Image with tag 'latest' does not exist. Skipping delete."
          fi

      - name: Docker Login to Google Artifact Registry
        run: docker login -u oauth2accesstoken -p "${{ steps.google_auth.outputs.access_token }}" ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Build and push to Google Artifact Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/${{ vars.GCP_REGISTRY_REPO }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ needs.test-pipeline.outputs.semVer }}
            ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/${{ vars.GCP_REGISTRY_REPO }}/${{ vars.DOCKER_IMAGE_NAME }}:latest

  azure-release:
    runs-on: ubuntu-latest
    needs: test-pipeline
    permissions:
      contents: write
      id-token: write
    env:
      ACR_REPO: udxmarketplace.azurecr.io
      FORCE: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate AZURE_CREDENTIALS from .udx
        run: |
          chmod +x ci/scripts/generate_azure_credentials.sh
          sh ci/scripts/generate_azure_credentials.sh

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: azure_credentials.json

      - name: Delete previous "latest" image from Azure Container Registry
        run: |
          IMAGE_NAME="${{ env.ACR_REPO }}/udx-worker"
          IMAGE_TAG="latest"
          IMAGE_DIGEST=$(az acr repository show-manifests --name ${{ env.ACR_REPO }} --repository udx-worker --query "[?tags[?contains(@, '${IMAGE_TAG}')]].digest" -o tsv)
          if [ -n "$IMAGE_DIGEST" ]; then
            az acr repository delete --name ${{ env.ACR_REPO }} --image "${IMAGE_NAME}@${IMAGE_DIGEST}" --yes
          else
            echo "Image with tag 'latest' does not exist. Skipping delete."
          fi

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ env.ACR_REPO }}

      - name: Build and push to Azure Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.ACR_REPO }}/udx-worker:${{ needs.test-pipeline.outputs.semVer }}
            ${{ env.ACR_REPO }}/udx-worker:latest

      - name: Clean up AZURE_CREDENTIALS
        run: |
          echo "AZURE_CREDENTIALS=" >> $GITHUB_ENV

  github-release:
    runs-on: ubuntu-latest
    needs: test-pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Create GitHub release
        run: bash ci/scripts/github_release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          semVer: ${{ needs.test-pipeline.outputs.semVer }}
          changelog: ${{ env.changelog }}