# GitHub Actions Workflow for Setting Up Azure Secrets v2
# This GitHub Actions workflow sets up the Azure credentials as secrets in the GitHub repository.
---
    name: Setup Azure Secrets
    
    on:
      workflow_dispatch:
        inputs:
          azure_credentials_json:
            description: "Paste your azure_credentials.json content here after running [az login]"
            required: true
            type: string
    
    jobs:
      setup-secrets:
        runs-on: ubuntu-latest
        name: Setup Azure Secrets
    
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
    
          - name: Extract Azure Credentials
            id: extract-creds
            run: |
              echo '${{ github.event.inputs.azure_credentials_json }}' > azure_credentials.json
              if ! jq -e . >/dev/null 2>&1 < azure_credentials.json; then
                echo "Error: Invalid JSON input"
                exit 1
              fi
              export UDX_AZURE_CLIENT_ID=$(jq -r '.clientId' azure_credentials.json)
              export UDX_AZURE_CLIENT_SECRET=$(jq -r '.clientSecret' azure_credentials.json)
              export UDX_AZURE_SUBSCRIPTION_ID=$(jq -r '.subscriptionId' azure_credentials.json)
              export UDX_AZURE_TENANT_ID=$(jq -r '.tenantId' azure_credentials.json)
              echo "UDX_AZURE_CLIENT_ID=$UDX_AZURE_CLIENT_ID" >> $GITHUB_ENV
              echo "UDX_AZURE_CLIENT_SECRET=$UDX_AZURE_CLIENT_SECRET" >> $GITHUB_ENV
              echo "UDX_AZURE_SUBSCRIPTION_ID=$UDX_AZURE_SUBSCRIPTION_ID" >> $GITHUB_ENV
              echo "UDX_AZURE_TENANT_ID=$UDX_AZURE_TENANT_ID" >> $GITHUB_ENV
    
          - name: Set GitHub Secrets
            env:
              UDX_AZURE_CLIENT_ID: ${{ env.UDX_AZURE_CLIENT_ID }}
              UDX_AZURE_CLIENT_SECRET: ${{ env.UDX_AZURE_CLIENT_SECRET }}
              UDX_AZURE_SUBSCRIPTION_ID: ${{ env.UDX_AZURE_SUBSCRIPTION_ID }}
              UDX_AZURE_TENANT_ID: ${{ env.UDX_AZURE_TENANT_ID }}
            run: |
              gh secret set UDX_AZURE_CLIENT_ID --body "$UDX_AZURE_CLIENT_ID"
              gh secret set UDX_AZURE_CLIENT_SECRET --body "$UDX_AZURE_CLIENT_SECRET"
              gh secret set UDX_AZURE_SUBSCRIPTION_ID --body "$UDX_AZURE_SUBSCRIPTION_ID"
              gh secret set UDX_AZURE_TENANT_ID --body "$UDX_AZURE_TENANT_ID"
    
          - name: Confirm Secret Creation
            run: |
              echo "Created secrets:"
              echo "UDX_AZURE_CLIENT_ID: ${{ env.UDX_AZURE_CLIENT_ID }}"
              echo "UDX_AZURE_CLIENT_SECRET: (hidden)"
              echo "UDX_AZURE_SUBSCRIPTION_ID: ${{ env.UDX_AZURE_SUBSCRIPTION_ID }}"
              echo "UDX_AZURE_TENANT_ID: ${{ env.UDX_AZURE_TENANT_ID }}"
    